name: Android CI/CD
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unitTest:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: actions/cache@v3.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Set up Local properties keys
        run: |
          echo FIREBASE_API_KEY=\"${{ secrets.FIREBASE_API_KEY }}\" >> ./local.properties
          echo FIREBASE_APPLICATION_ID=\"${{ secrets.FIREBASE_APPLICATION_ID }}\" >> ./local.properties
          echo FIREBASE_CLIENT_ID=\"${{ secrets.FIREBASE_CLIENT_ID }}\" >> ./local.properties
          echo FIREBASE_DATABASE_URL=\"${{ secrets.FIREBASE_DATABASE_URL }}\" >> ./local.properties
          echo FIREBASE_PROJECT_ID=\"${{ secrets.FIREBASE_PROJECT_ID }}\" >> ./local.properties

      - name: Run local tests
        run: ./gradlew testDebug --stacktrace

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/build/test-results/**/*.xml"