name: Android CI/CD
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unitTest:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: actions/cache@v3.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Check lint
        run: ./gradlew lintDebug --stacktrace

      - name: Build debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Build release
        run: ./gradlew assembleRelease --stacktrace

      - name: Run local tests
        run: ./gradlew testDebug --stacktrace

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "app/build/reports/tests/testDebugUnitTest/index.html"