name: Android CI/CD
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unitTest:
    name: Unit tests
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: amyu/setup-android@v1.1
        with:
          is-use-cache: false
          sdk-version: '32'
          build-tools-version: '32.0.0'

      - name: Copy CI gradle.properties
        run: mkdir -p /home/stslex/actions-runner/_work/CNotes/CNotes/.gradle ; cp .github/ci-gradle.properties /home/stslex/actions-runner/_work/CNotes/CNotes/.gradle/gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: actions/cache@v3.0.2
        with:
          path: |
            /home/stslex/actions-runner/_work/CNotes/CNotes/.gradle/caches
            /home/stslex/actions-runner/_work/CNotes/CNotes/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Set up Local properties keys
        run: |
          echo FIREBASE_API_KEY=\"${{ secrets.FIREBASE_API_KEY }}\" >> /home/stslex/actions-runner/_work/CNotes/CNotes./local.properties
          echo FIREBASE_APPLICATION_ID=\"${{ secrets.FIREBASE_APPLICATION_ID }}\" >> /home/stslex/actions-runner/_work/CNotes/CNotes./local.properties
          echo FIREBASE_CLIENT_ID=\"${{ secrets.FIREBASE_CLIENT_ID }}\" >> /home/stslex/actions-runner/_work/CNotes/CNotes./local.properties
          echo FIREBASE_DATABASE_URL=\"${{ secrets.FIREBASE_DATABASE_URL }}\" >> /home/stslex/actions-runner/_work/CNotes/CNotes./local.properties
          echo FIREBASE_PROJECT_ID=\"${{ secrets.FIREBASE_PROJECT_ID }}\" >> /home/stslex/actions-runner/_work/CNotes/CNotes./local.properties

      - name: Check lint
        run: ./gradlew lintDebug --stacktrace

      - name: Build debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Build release
        run: ./gradlew assembleRelease --stacktrace

      - name: Run local tests
        run: ./gradlew testDebug --stacktrace