name: Android CI/CD
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unitTest:
    name: Unit tests
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Copy CI gradle.properties
        run: mkdir -p secrets.PATH_PROJECT/.gradle ; cp .github/ci-gradle.properties secrets.PATH_PROJECT/.gradle/gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: actions/cache@v3.0.2
        with:
          path: |
            secrets.PATH_PROJECT/.gradle/caches
            secrets.PATH_PROJECT/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('secrets.PATH_PROJECT/**/*.gradle*', 'secrets.PATH_PROJECT/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Set up Local properties keys
        run: |
          echo FIREBASE_API_KEY=\"${{ secrets.FIREBASE_API_KEY }}\" >> secrets.PATH_PROJECT/.local.properties
          echo FIREBASE_APPLICATION_ID=\"${{ secrets.FIREBASE_APPLICATION_ID }}\" >> secrets.PATH_PROJECT/.local.properties
          echo FIREBASE_CLIENT_ID=\"${{ secrets.FIREBASE_CLIENT_ID }}\" >> secrets.PATH_PROJECT/.local.properties
          echo FIREBASE_DATABASE_URL=\"${{ secrets.FIREBASE_DATABASE_URL }}\" >> secrets.PATH_PROJECT/.local.properties
          echo FIREBASE_PROJECT_ID=\"${{ secrets.FIREBASE_PROJECT_ID }}\" >> secrets.PATH_PROJECT/.local.properties
          echo sdk.dir=\"${{ secrets.PATH_SDK }}\" >> secrets.PATH_PROJECT/.local.properties

      - name: Check lint
        run: ./gradlew lintDebug --status --stacktrace

      - name: Build debug
        run: ./gradlew assembleDebug --status --stacktrace

      - name: Build release
        run: ./gradlew assembleRelease --status --stacktrace

      - name: Run local tests
        run: ./gradlew testDebug --status --stacktrace

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          disable-animations: true
          disk-size: 1500M
          heap-size: 512M
          script: ./gradlew connectedAndroidTest